apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
spec:
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
{{- range .Values.volume.accessModes }}
    - {{ . | quote }}
{{- end }}
  nfs:
    server: {{ .Values.volume.nfs_server }}
    path: {{ .Values.volume.nfs_path }}
