- name: Update apt packages on supported machines
  hosts: apt_hosts
  become: true
  gather_facts: true

  tasks:
    - name: Ensure system is Debian/Ubuntu-based
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == 'Debian'
        fail_msg: "This playbook only supports Debian/Ubuntu systems. Detected: {{ ansible_facts['os_family'] }}"
      tags: [check]

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [update]

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      tags: [upgrade]

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: yes
      tags: [cleanup, autoremove]

    - name: Autoclean package cache
      ansible.builtin.apt:
        autoclean: yes
      tags: [cleanup, autoclean]

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      tags: [reboot, check]

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot triggered after package upgrades"
        connect_timeout: 5
        reboot_timeout: 600
      when: reboot_required.stat.exists
      tags: [reboot]
